apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mqtt-pubsub
spec:
  type: pubsub.mqtt3
  version: v1
  metadata:
  - name: url
    value: "tcp://127.0.0.1:1884"
  - name: qos
    value: "1"
  - name: retain
    value: "false"
  - name: cleanSession
    value: "true"
  - name: enableRawPayload
    value: "true"
